# SIIMUT — Sistem Informasi Imunisasi
name: siimut
role: standalone
repo: https://github.com/juniyasyos/si-imut.git
branch: main
source_dir: siimut
image: juniyasyos/siimut
version: v2.1.0
port: 8000
domain: siimut.local
database: siimut_db
db_user: siimut_user
queue: true
scheduler: true
php_version: "8.4"
has_prod_env: true
has_local_deps: false
description: SIIMUT - Sistem Informasi Imunisasi
