# {{APP_DESC}}
name: {{APP_NAME}}
repo: {{APP_REPO}}
branch: {{APP_BRANCH}}
source_dir: {{SOURCE_DIR}}
image: {{IMAGE_NAME}}
version: {{IMAGE_VERSION}}
port: {{APP_PORT}}
domain: {{APP_DOMAIN}}
database: {{DB_NAME}}
db_user: {{DB_USER}}
db_password: {{DB_PASSWORD}}
queue: {{HAS_QUEUE}}
scheduler: {{HAS_SCHEDULER}}
php_version: "{{PHP_VERSION}}"
has_prod_env: {{HAS_PROD_ENV}}
has_local_deps: {{HAS_LOCAL_DEPS}}
description: {{APP_DESC}}