name: service-lms

services:
  app:
    extends:
      file: ../base/common.yml
      service: php-app-base
    image: lms-app:v1.0.0
    container_name: lms-app
    working_dir: /var/www/lms-app
    env_file:
      - ../../apps/lms/.env.example
    environment:
      APP_ENV: production
      APP_DEBUG: "true"
      APP_WORKDIR: /var/www/lms-app
      PUBLIC_VOLUME: /var/www/lms-app/public
      APP_URL: "http://192.168.1.9:7000"
      TRUSTED_PROXIES: "*"
      DB_HOST: database-service
      DB_USERNAME: lms_user
      DB_PASSWORD: lms-password
      DB_DATABASE: db_lms_citrahusada
    volumes:
      - lms_storage:/var/www/lms-app/storage
      - lms_bootstrap_cache:/var/www/lms-app/bootstrap/cache
      - lms_public:/var/www/lms-app/public
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_ADMIN
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: "1"
        reservations:
          memory: 512M
          cpus: "0.5"

  queue:
    extends:
      file: ../base/common.yml
      service: php-worker-base
    image: lms-app:v1.0.0
    container_name: lms-queue
    working_dir: /var/www/lms-app
    env_file:
      - ../../apps/lms/.env.example
    environment:
      APP_URL: "http://192.168.1.9:7000"
      DB_HOST: database-service
      DB_USERNAME: lms_user
      DB_PASSWORD: lms-password
      DB_DATABASE: db_lms_citrahusada
    volumes:
      - lms_storage:/var/www/lms-app/storage
      - lms_bootstrap_cache:/var/www/lms-app/bootstrap/cache
      - lms_public:/var/www/lms-app/public
    command: >
      artisan queue:work
        --sleep=5
        --tries=3
        --timeout=120
        --max-jobs=500
        --max-time=3600
    deploy:
      resources:
        limits:
          memory: 384M
          cpus: "0.7"
        reservations:
          memory: 128M
          cpus: "0.25"

  scheduler:
    extends:
      file: ../base/common.yml
      service: php-scheduler-base
    image: lms-app:v1.0.0
    container_name: lms-scheduler
    working_dir: /var/www/lms-app
    env_file:
      - ../../apps/lms/.env.example
    environment:
      APP_URL: "http://192.168.1.9:7000"
      DB_HOST: database-service
      DB_USERNAME: lms_user
      DB_PASSWORD: lms-password
      DB_DATABASE: db_lms_citrahusada
    volumes:
      - lms_storage:/var/www/lms-app/storage
      - lms_bootstrap_cache:/var/www/lms-app/bootstrap/cache
      - lms_public:/var/www/lms-app/public
    command: >
      artisan schedule:work
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: "0.2"
        reservations:
          memory: 64M
          cpus: "0.1"